export function renderKeaViewerHtml(): string {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>Kea · decipher and audit</title>
  <style>
    :root{color-scheme:dark;--bg:#080b0d;--panel:#101519;--line:#263037;--ink:#edf4f1;--muted:#8fa09b;--kea:#89f7c5;--warn:#ffcb77;--bad:#ff7e8d;--blue:#8ab8ff}
    *{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 16% -12%,#16342d 0,transparent 32%),radial-gradient(circle at 92% 18%,#17233d 0,transparent 30%),var(--bg);color:var(--ink);font:14px/1.5 ui-sans-serif,system-ui,-apple-system,sans-serif;min-height:100vh}
    header{height:68px;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:0 24px;background:rgba(8,11,13,.8);backdrop-filter:blur(18px);position:sticky;top:0;z-index:3}.brand{display:flex;align-items:center;gap:12px}.mark{width:34px;height:34px;border:1px solid #4c7668;border-radius:12px;display:grid;place-items:center;background:linear-gradient(145deg,#16332b,#0d1615);color:var(--kea);font-weight:800}.brand b{font-size:17px;letter-spacing:.02em}.brand small{display:block;color:var(--muted);font-size:11px}.badge{border:1px solid #35584d;border-radius:999px;padding:5px 10px;color:var(--kea);font-size:11px;text-transform:uppercase;letter-spacing:.08em}
    main{display:grid;grid-template-columns:minmax(280px,390px) 1fr;gap:16px;padding:16px;min-height:calc(100vh - 68px)}.panel{background:linear-gradient(180deg,rgba(18,24,28,.94),rgba(12,16,19,.94));border:1px solid var(--line);border-radius:18px;overflow:hidden;box-shadow:0 18px 50px rgba(0,0,0,.18)}.panel-head{padding:16px 18px;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between}.panel-head h2{font-size:13px;margin:0;text-transform:uppercase;letter-spacing:.09em;color:var(--muted)}button{font:inherit}.refresh{border:1px solid var(--line);background:#11191c;color:var(--ink);border-radius:9px;padding:6px 9px;cursor:pointer}.list{padding:8px;max-height:calc(100vh - 150px);overflow:auto}.item{width:100%;text-align:left;border:1px solid transparent;background:transparent;color:var(--ink);padding:12px;border-radius:12px;cursor:pointer}.item:hover,.item.active{background:#14201f;border-color:#2c4941}.item .top{display:flex;justify-content:space-between;gap:12px}.item strong{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.item time{font-size:10px;color:var(--muted)}.item p{margin:4px 0 0;color:var(--muted);font-size:12px}.empty{padding:36px 20px;color:var(--muted);text-align:center}
    .detail{padding:22px;overflow:auto;max-height:calc(100vh - 102px)}.hero{border:1px solid var(--line);background:linear-gradient(145deg,#111a1c,#0c1114);padding:20px;border-radius:16px}.eyebrow{color:var(--kea);font-size:11px;letter-spacing:.1em;text-transform:uppercase}.hero h1{font-size:25px;margin:8px 0 6px}.hero p{color:var(--muted);margin:0}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin-top:14px}.metric{border:1px solid var(--line);border-radius:12px;padding:12px;background:#0c1113}.metric span{display:block;color:var(--muted);font-size:10px;text-transform:uppercase;letter-spacing:.07em}.metric b{display:block;margin-top:4px;font-size:15px}.good{color:var(--kea)}.warning{color:var(--warn)}.bad{color:var(--bad)}section{margin-top:16px;border:1px solid var(--line);border-radius:14px;overflow:hidden}section h3{font-size:11px;text-transform:uppercase;letter-spacing:.09em;color:var(--muted);padding:12px 14px;margin:0;border-bottom:1px solid var(--line)}pre{margin:0;padding:14px;white-space:pre-wrap;word-break:break-word;color:#c9d8d3;background:#0a0e10;font:12px/1.55 ui-monospace,SFMono-Regular,Menlo,monospace}.signal{padding:10px 14px;border-bottom:1px solid var(--line)}.signal:last-child{border:0}.signal b{font-size:12px}.signal small{display:block;color:var(--muted);margin-top:2px}
    @media(max-width:820px){main{grid-template-columns:1fr}.list{max-height:310px}.detail{max-height:none}.grid{grid-template-columns:1fr}}
  </style>
</head>
<body>
  <header><div class="brand"><div class="mark">K</div><div><b>Kea</b><small>decipher · replay · watch · decompose · budget</small></div></div><div class="badge" id="mode">fixture-only</div></header>
  <main>
    <aside class="panel"><div class="panel-head"><h2>Recorded messages</h2><button class="refresh" id="refresh">Refresh</button></div><div class="list" id="list"><div class="empty">No fixture messages recorded.</div></div></aside>
    <article class="panel detail" id="detail"><div class="hero"><div class="eyebrow">Separate measurement plane</div><h1>Legibility is a tap, never the transport.</h1><p>Select a message to inspect its content-addressed envelope, exact decoder result, alternatives, watch signals, capacity budget, and correction history.</p><div class="grid" id="status"></div></div></article>
  </main>
  <script>
    const esc=(v)=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
    const json=(v)=>esc(JSON.stringify(v,null,2));
    async function api(path){const r=await fetch(path,{headers:{accept:'application/json'}});const j=await r.json();if(!r.ok)throw new Error(j.error||r.statusText);return j}
    function metric(label,value,cls=''){return '<div class="metric"><span>'+esc(label)+'</span><b class="'+cls+'">'+esc(value)+'</b></div>'}
    async function load(){const [s,m]=await Promise.all([api('/api/status'),api('/api/messages?limit=100')]);document.querySelector('#mode').textContent=s.mode;document.querySelector('#status').innerHTML=metric('ledger',s.ledgerEvents+' events','good')+metric('decoders',s.decoders)+metric('authority','never granted','good');const list=document.querySelector('#list');if(!m.messages.length){list.innerHTML='<div class="empty">No fixture messages recorded.<br/>Use <code>kea fixture</code> to create one.</div>';return}list.innerHTML=m.messages.map(x=>'<button class="item" data-id="'+esc(x.messageId)+'"><div class="top"><strong>'+esc(x.messageClass)+' · '+esc(x.workNodeId)+'</strong><time>'+esc(x.createdAt.slice(11,19))+'</time></div><p>'+esc(x.codec.codecId)+' · '+esc(x.payloadBytes)+' bytes</p></button>').join('');list.querySelectorAll('.item').forEach(b=>b.onclick=()=>openReplay(b.dataset.id,b));}
    async function openReplay(id,button){document.querySelectorAll('.item').forEach(x=>x.classList.remove('active'));button?.classList.add('active');const r=await api('/api/replay/'+encodeURIComponent(id));const i=r.interpretations.at(-1);const signals=(i?.watchSignals||[]).map(s=>'<div class="signal"><b class="'+(s.severity==='block'?'bad':'warning')+'">'+esc(s.code)+'</b><small>'+esc(s.detail)+'</small></div>').join('')||'<div class="signal"><b class="good">No blocking signals</b></div>';document.querySelector('#detail').innerHTML='<div class="hero"><div class="eyebrow">'+esc(i?.disposition||'unread')+'</div><h1>'+esc(i?.humanGloss||'No interpretation')+'</h1><p>'+esc(r.message.messageClass)+' · '+esc(r.message.codec.codecId)+'@'+esc(r.message.codec.codecVersion)+'</p><div class="grid">'+metric('round trip',i?.verification?.exactRoundTrip===true?'exact':'qualified',i?.verification?.exactRoundTrip===true?'good':'warning')+metric('capacity',i?.budget?.exceeded?'blocked':'within budget',i?.budget?.exceeded?'bad':'good')+metric('authority',i?.authorityGranted?'invalid':'none',i?.authorityGranted?'bad':'good')+'</div></div><section><h3>Watch</h3>'+signals+'</section><section><h3>Decomposition</h3><pre>'+json(i?.decomposition||{})+'</pre></section><section><h3>Immutable envelope</h3><pre>'+json(r.message)+'</pre></section><section><h3>Interpretations and corrections</h3><pre>'+json({interpretations:r.interpretations,corrections:r.corrections})+'</pre></section>';}
    document.querySelector('#refresh').onclick=load;load().catch(e=>document.querySelector('#list').innerHTML='<div class="empty bad">'+esc(e.message)+'</div>');
  </script>
</body></html>`;
}
